version: "3.3"
services:
  web:
    build: backend
    ports:
      - "5000:5000"
    links:
     - db
    depends_on:
     - db
    volumes: ['./backend:/app']
  db:
    image: mongo
    ports:
      - "27017:27017"
